server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zss0527/cloud2023-config.git
          search-paths:
            - cloud2023-config
      label: master

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://localhost:7002/eureka

management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"