server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    #if register self as instance
    register-with-eureka: false
    #if self is register center
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
